name = "MyPkgTemplate"
uuid = "e8293b1b-19cc-4f1f-a802-67e674c34b4a"
authors = ["JingYu Ning <foldfelis@gmail.com> and contributors"]
version = "0.1.0"

[deps]
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"

[compat]
PkgTemplates = "0.7"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
